CREATE SCHEMA IF NOT EXISTS logs;

CREATE TABLE IF NOT EXISTS logs.request_log (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  endpoint VARCHAR (255) NOT NULL,
  parameters TEXT NOT NULL,
  response TEXT NOT NULL,
  status_code INTEGER NOT NULL
);