version: '3'

services:
  percentage-service:
    container_name: percentage-service
    image: fedesartu/percentage-service
    restart: on-failure
    depends_on:
      - redis
      - db
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    ports:
      - '8085:8080'
  db:
    container_name: postgres-database
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - '5432:5432'
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8050:8080
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    expose:
      - 6379
